import Head from "next/head";

import Hero from "../components/hero.component";
import Aboutme from "../components/aboutme.component";
import Portfolio from "../components/portfolio.component";
import Service from "../components/service.component";
import Resume from "../components/resume.component";
import Testimonials from "../components/testimonials.component";
import Statistics from "../components/statistics.component";
import Contact from "../components/contact.component";
import Conferences from "../components/conferrences.component";
import Trusted from "../components/trusted.component";
import Roadmap from "../components/roadmap.component";
import Fade from "react-reveal/Fade";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mohamed Fadel Moumeni.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Aboutme />
      <Service />
      <Resume />
      <Conferences />
      <Trusted />
      <Testimonials />
      <Statistics />
      <Contact />
      <Roadmap />
    </div>
  );
}
